### ISSUE TITLE
API change in saul/phydat

### ISSUE THREAD

**Issue by Teufelchen1** [RIOT-OS/rust-riot-wrappers#86]
Hi! :leopard: 

This:
https://github.com/RIOT-OS/rust-riot-wrappers/blob/409a5bea642c8b9aeb765676f62884763b3524f4/src/saul.rs#L488-L502

needs to be changed to something like this:
```Rust
#[doc(alias = "phydat_unit_write")]
pub fn name(self) -> Option<&'static str> {
    unsafe {
        let mut buffer: char = [0; 10];
        riot_sys::phydat_unit_write(buffer, 10, Self::to_c(Some(self)));
        str::from_utf8(buffer)
    }.ok()
}
```

in order for this PR https://github.com/RIOT-OS/RIOT/pull/20529 to get merged. Otherwise `RIOT/examples/rust-gcoap` can not be [build](https://ci.riot-os.org/details/83a70b20515444de9f4d89504438b5ec).

How do we approach this? :chicken: :repeat: :egg:

**Comment by Teufelchen1** [comment]
I am afraid it is:
[phydat.h](https://github.com/RIOT-OS/RIOT/blob/a9e7b441a7be21a90a26bbd199afa060f3646559/sys/include/phydat.h#L206-L229)
```C
/**
 * @brief   Print a unit
 *
 * @param[in] unit          unit to print
 */
void phydat_unit_print(uint8_t unit);

/**
 * @brief   Write the string representation of the given unit into the given
 *          buffer
 *
 * @param[out]  dest        destination buffer to write to
 * @param[in]   max_size    size of the buffer at @p dest
 * @param[in]   unit        unit to convert
 *
 * @return  Number of bytes written
 * @retval  -EOVERFLOW      buffer at @p dest is too small
 * @retval  -EINVAL         invalid unit in @p unit
 *
 * @warning The function will never write a terminating zero byte
 * @note    If you pass `NULL` for @p dest, it will return the number of bytes
 *          it would write (regardless of @p max_size)
 */
ssize_t phydat_unit_write(char *dest, size_t max_size, uint8_t unit);
```

**Comment by chrysn** [comment]
Ah, this is one of those Harvard architecture workarounds. Worst case the lookup can be turned to always return None; are there viable alternatives?

**Comment by chrysn** [comment]
The ideal answer I'd like to give is "here's what we need for Rust to just do the right thing on AVR and the rest of the world", but without a running AVR port I can't give that yet :-(

**Comment by maribu** [comment]
This may not be popular, but I think the honest thing to do is to acknowledge that large read-only databases in address space is something we cannot provide in a portable embedded OS. Hence, the Rust API should also be adapted.

Also: For users the new C API is actually more convenient. The two main use cases is printing out the information or writing it into a buffer as part of constructing some CBOR / JSON / foobar-serialization. A similar API change on the Rust side will also be more convenient for new users and quick to fix for existing users.

**Comment by chrysn** [comment]
I'd be more convinced if I such external storage were actually used here, but am convinced enough to not block this. I'll follow up with a PR on the riot-wrappers side, and ask you for feedback there.
