### ISSUE TITLE
vfs: error when opening files from constfs filesystem

### ISSUE THREAD

**Issue by maikerlab** [RIOT-OS/rust-riot-wrappers#93]
In my RIOT application I initialize the constfs file system and some private data in a c-file, exactly like in the [filesystem example](https://github.com/RIOT-OS/RIOT/tree/master/examples/filesystem) (with `vfs_mount`).
I can also open and read the contents inside the file (e. g. with `fopen("/const/dac", "r")` and `open("/const/dac", O_RDONLY)`)
Reading from shell is also possible (e.g. with `vfs r /const/dac 15 0`)

In my Rust code, I first call the external C-Function, where `vfs_mount` gets called.
When iterating over all mount points with `vfs::Mount::all()` and files inside `/const`, everything looks as expected and the desired files exist.
But when trying to open a file (e.g. with `vfs::File::open("/const/dac")`, I get an error (`-2` ENOENT 2 No such file or directory)

I could reproduce this error on `native` and `nucleo-f429zi` board

**Comment by chrysn** [comment]
Just for reference (not sure when I get around to fixing this), this was known at https://gitlab.com/etonomy/riot-wrappers/-/issues/8 (but only tracked in this tracker through https://github.com/RIOT-OS/rust-riot-wrappers/issues/26).

**Comment by chrysn** [comment]
I stand corrected: This is a different bug than the old issue 8.

Investigating…
